#!/bin/bash

set -euo pipefail

file=$(basename $1)

indexout=$(echo -n "$(date +%Y-%m-%d)" \
"$(crc32 $file)" \
"$(echo $file.zip)")

zip "$file.zip" $file
sed -i /$file/d .index-extended
echo "$indexout" >> .index-extended
sed -i /$file/d .index
echo "$file" >> .index

rm $file
